# Generated by Django 5.0.4 on 2024-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FellbladeDemonHunter',
            new_name='FelbladeDemonHunter',
        ),
    ]
