# Generated by Django 5.0.4 on 2024-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weatherforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='humidity',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
