# Generated by Django 5.0.4 on 2024-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_department_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Employees Count',
        ),
        migrations.AddField(
            model_name='department',
            name='employees_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Employees Count'),
        ),
    ]
