# Generated by Django 5.0.4 on 2024-06-26 09:42

from django.db import migrations


def assign_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')

    items = item.objects.all()

    for record in items:
        if record.price <= 10:
            record.rarity = 'Rare'
        elif record.price <= 20:
            record.rarity = 'Very Rare'
        elif record.price <= 30:
            record.rarity = 'Extremely Rare'
        else:
            record.rarity = 'Mega Rare'

    item.objects.bulk_update(items, ['rarity'])


def reverse_assign_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.object.all()

    for record in items:
        record.rarity = item._meta.get_field('rarity').default

    item.objects.bulk_update(items, ['rarity'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(assign_rarity, reverse_assign_rarity)
    ]
